username = "testgosro1@cigma.nl"
password = [
    93,
    107,
    224,
    109,
    177,
    21,
    223,
    76,
    232,
    163,
    149,
    56,
    60,
    91,
    172,
    77,
    112,
    101,
    160,
    107,
    63,
    246,
    216,
    60,
    71,
    214,
    236,
    246,
    102,
    236,
    24,
    200,
    3,
    122,
    62,
    62,
    38,
]
nonce = [
    6,
    59,
    170,
    146,
    195,
    164,
    160,
    197,
    106,
    59,
    117,
    90,
]

[relay]
addr = "smtp.office365.com"
port = 587
tls = true
authentication = ["Login"]
